---
title: Dockerfile を指定して、W&B に Docker イメージをビルドさせることはできますか？
---

この機能は、要件は安定している一方で、コードベースが頻繁に変更されるプロジェクトに適しています。

<Warning>
Dockerfile はマウントを利用する形式で記述してください。詳しくは [Docker Docs ウェブサイトの Mounts ドキュメント](https://docs.docker.com/build/guide/mounts/)を参照してください。
</Warning>

Dockerfile を設定したら、次の 3 通りのいずれかの方法で W&B に指定します。

* Dockerfile.wandb を使う
* W&B CLI を使う
* W&B App を使う

<Tabs>
<Tab title="Dockerfile.wandb">
W&B の run のエントリポイントと同じディレクトリに `Dockerfile.wandb` ファイルを配置してください。W&B は組み込みの Dockerfile の代わりにこのファイルを使用します。
</Tab>
<Tab title="W&B CLI">
`wandb launch` コマンドで `--dockerfile` フラグを使ってジョブをキューに追加します:

```bash
wandb launch --dockerfile path/to/Dockerfile
```
</Tab>
<Tab title="W&B app">
W&B App でキューにジョブを追加するとき、**Overrides** セクションで Dockerfile のパスを指定します。キーを `"dockerfile"`、値を Dockerfile へのパスとするキーと値のペアとして入力します。

次の JSON は、ローカルディレクトリ内の Dockerfile を含める方法を示しています。

```json title="Launch job W&B App"
{
  "args": [],
  "run_config": {
    "lr": 0,
    "batch_size": 0,
    "epochs": 0
  },
  "entrypoint": [],
  "dockerfile": "./Dockerfile"
}
```
</Tab>
</Tabs>