---
title: Dockerfile を指定して、W&B に Docker イメージをビルドさせることができますか？
---

この機能は、要件が安定している一方でコードベースが頻繁に変更されるプロジェクトに適しています。

<Warning>
  Dockerfile をマウントを使用する形式にフォーマットしてください。詳細については、[Docker Docs ウェブサイトの Mounts ドキュメント](https://docs.docker.com/build/guide/mounts/) を参照してください。
</Warning>

Dockerfile を設定したら、次の 3 つの方法のいずれかで W&amp;B に指定します。

* Dockerfile.wandb を使用する
* W&amp;B CLI を使用する
* W&amp;B App を使用する

<Tabs>
  <Tab title="Dockerfile.wandb">
    W&amp;B run のエントリーポイントと同じディレクトリに `Dockerfile.wandb` ファイルを配置してください。W&amp;B はビルトインの Dockerfile の代わりにこのファイルを使用します。
  </Tab>

  <Tab title="W&B CLI">
    `wandb launch` コマンドに `--dockerfile` フラグを指定してジョブをキューに登録します。

    ```bash
    wandb launch --dockerfile path/to/Dockerfile
    ```
  </Tab>

  <Tab title="W&B app">
    W&amp;B App でキューにジョブを追加する際は、**Overrides** セクションで Dockerfile のパスを指定してください。キーを `"dockerfile"`、値を Dockerfile のパスとして、キー・バリューのペアで入力します。

    次の JSON は、ローカルディレクトリ内の Dockerfile を指定する方法の例です。

    ```json title="Launch ジョブ W&B App"
    {
      "args": [],
      "run_config": {
        "lr": 0,
        "batch_size": 0,
        "epochs": 0
      },
      "entrypoint": [],
      "dockerfile": "./Dockerfile"
    }
    ```
  </Tab>
</Tabs>