extends: existence
message: "Images must include non-empty alt text"
link: "https://weave-docs.wandb.ai" # Placeholder link; update if there is a specific internal style guide page
level: error
scope: raw
ignorecase: true
tokens:
  # Markdown images with empty or whitespace-only alt text: ![](path) or ![   ](path)
  - '!\[\s*\]\('
  # HTML <img> with an empty alt attribute: <img alt=""> or <img alt='  '>
  - '<img[^>]*alt\s*=\s*"\s*"[^>]*>'
  - '<img[^>]*alt\s*=\s*''\s*''[^>]*>'
