---
title: Dockerfile을 지정하고 W&B가 대신 Docker 이미지를 빌드해 줄 수 있나요?
---

이 기능은 요구 사항은 안정적이지만 코드베이스는 자주 변경되는 프로젝트에 적합합니다.

<Warning>
Dockerfile에서 마운트를 사용하도록 작성하세요. 자세한 내용은 [Docker Docs 웹사이트의 Mounts 문서](https://docs.docker.com/build/guide/mounts/)를 참조하세요.
</Warning>

Dockerfile을 구성한 후, 다음 세 가지 방법 중 하나로 W&B에 Dockerfile을 지정할 수 있습니다:

* Dockerfile.wandb 사용
* W&B CLI 사용
* W&B App 사용

<Tabs>
<Tab title="Dockerfile.wandb">
`Dockerfile.wandb` 파일을 W&B 실행 엔트리 포인트와 동일한 디렉터리에 두세요. W&B는 기본 제공 Dockerfile 대신 이 파일을 사용합니다.
</Tab>
<Tab title="W&B CLI">
`wandb launch` 명령과 함께 `--dockerfile` 플래그를 사용해 작업을 큐에 추가하세요:

```bash
wandb launch --dockerfile path/to/Dockerfile
```
</Tab>
<Tab title="W&B App">
W&B App에서 작업을 큐에 추가할 때 **Overrides** 섹션에 Dockerfile 경로를 입력하세요. `"dockerfile"`을 키로, Dockerfile 경로를 값으로 하는 키-값 쌍으로 입력합니다.

다음 JSON은 로컬 디렉터리에 있는 Dockerfile을 포함하는 방법을 보여줍니다:

```json title="W&B App에서 작업 실행"
{
  "args": [],
  "run_config": {
    "lr": 0,
    "batch_size": 0,
    "epochs": 0
  },
  "entrypoint": [],
  "dockerfile": "./Dockerfile"
}
```
</Tab>
</Tabs>