---
title: Puis-je spécifier un Dockerfile et laisser W&B effectuer le build d’une image Docker pour moi ?
---

Cette fonctionnalité convient aux projets dont les exigences sont stables, mais dont le code source change fréquemment.

<Warning>
  Rédigez votre Dockerfile de façon à utiliser des montages. Pour plus de détails, consultez la [documentation sur les montages du site Docker Docs](https://docs.docker.com/build/guide/mounts/).
</Warning>

Après avoir configuré le Dockerfile, indiquez-le à W&amp;B de l’une des trois façons suivantes :

* Utilisez Dockerfile.wandb
* Utilisez W&amp;B CLI
* Utilisez W&amp;B App

<Tabs>
  <Tab title="Dockerfile.wandb">
    Incluez un fichier `Dockerfile.wandb` dans le même répertoire que le point d’entrée du run W&amp;B. W&amp;B utilise ce fichier à la place du Dockerfile intégré par défaut.
  </Tab>

  <Tab title="W&B CLI">
    Utilisez l’indicateur `--dockerfile` avec la commande `wandb launch` pour ajouter un job à une file d&#39;attente :

    ```bash
    wandb launch --dockerfile path/to/Dockerfile
    ```
  </Tab>

  <Tab title="W&B app">
    Lorsque vous ajoutez un job à une file d&#39;attente dans la W&amp;B App, indiquez le chemin du Dockerfile dans la section **Overrides**. Saisissez-le sous forme de paire clé-valeur, avec `"dockerfile"` comme clé et le chemin vers le Dockerfile comme valeur.

    Le JSON suivant montre comment inclure un Dockerfile dans un répertoire local :

    ```json title="Lancer un job dans W&B App"
    {
      "args": [],
      "run_config": {
        "lr": 0,
        "batch_size": 0,
        "epochs": 0
      },
      "entrypoint": [],
      "dockerfile": "./Dockerfile"
    }
    ```
  </Tab>
</Tabs>