name: Alt Text Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'content/**/*.md'
      - 'content/**/*.html'

jobs:
  check-alt-text:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openai anthropic beautifulsoup4 lxml

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: |
          content/**/*.md
          content/**/*.html

    - name: Check alt text
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        python .github/scripts/alt-text-checker.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        PR_NUMBER: ${{ github.event.number }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }} 