name: Generate Weave references

on:
  workflow_dispatch:
    inputs:
      weave_version:
        description: 'A Weave version from PyPI (without -dev0 suffix) or "latest"'
        required: false
        default: 'latest'
        type: string

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
        
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('scripts/reference-generation/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install requests for Service API generation
      run: |
        pip install requests
        
    - name: Set version variable
      id: version
      run: |
        VERSION="${{ github.event.inputs.weave_version }}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Using Weave version: ${VERSION}"
        
        # Generate timestamp
        TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
        echo "Generated at: ${TIMESTAMP}"
        
    - name: Generate Service API Documentation
      run: |
        echo "Generating Service API documentation..."
        python scripts/reference-generation/generate_service_api_spec.py
        
    - name: Generate Python SDK Documentation
      id: python-sdk
      run: |
        echo "Generating Python SDK documentation..."
        VERSION="${{ steps.version.outputs.version }}"
        echo "Using Weave version: ${VERSION}"
        
        # Create isolated environment for Python SDK generation
        python -m venv venv_python
        source venv_python/bin/activate
        pip install requests lazydocs
        
        # Run the script and capture output for version extraction
        OUTPUT=$(python scripts/reference-generation/generate_python_sdk_docs.py "${VERSION:-latest}")
        echo "$OUTPUT"
        
        # Extract actual version if it was resolved
        ACTUAL_VERSION=$(echo "$OUTPUT" | grep "^ACTUAL_VERSION=" | cut -d= -f2)
        if [ -n "$ACTUAL_VERSION" ]; then
          echo "actual_version=${ACTUAL_VERSION}" >> $GITHUB_OUTPUT
        else
          echo "actual_version=${VERSION:-latest}" >> $GITHUB_OUTPUT
        fi
        
        deactivate
        rm -rf venv_python
        
    - name: Generate TypeScript SDK Documentation  
      run: |
        echo "Generating TypeScript SDK documentation..."
        VERSION="${{ steps.version.outputs.version }}"
        echo "Using Weave version: ${VERSION}"
        
        # Create isolated environment for TypeScript SDK generation
        python -m venv venv_typescript
        source venv_typescript/bin/activate
        python scripts/reference-generation/generate_typescript_sdk_docs.py "${VERSION:-latest}"
        deactivate
        rm -rf venv_typescript
        
    - name: Fix file casing
      run: |
        echo "Fixing file casing for SDK documentation..."
        python scripts/reference-generation/fix_casing.py
        
    - name: Update TOC
      run: |
        echo "Updating docs.json TOC with new Python SDK modules..."
        WEAVE_VERSION="${{ steps.python-sdk.outputs.actual_version || steps.version.outputs.version }}" python scripts/reference-generation/update_weave_toc.py
        
    - name: Fix broken links
      run: |
        echo "Fixing broken links in documentation..."
        python scripts/reference-generation/fix_broken_links.py
        
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: Update reference documentation (Weave ${{ steps.python-sdk.outputs.actual_version || steps.version.outputs.version }})"
        title: "Update Weave reference documentation (Weave ${{ steps.python-sdk.outputs.actual_version || steps.version.outputs.version }})"
        draft: true
        body: |
          This PR updates the reference documentation for Weave.
          
          **Version**: ${{ steps.python-sdk.outputs.actual_version || steps.version.outputs.version }}
          **Generated on**: ${{ steps.version.outputs.timestamp }}
          **Source code**: [wandb/weave@${{ steps.python-sdk.outputs.actual_version || steps.version.outputs.version }}](https://github.com/wandb/weave/tree/${{ steps.python-sdk.outputs.actual_version || steps.version.outputs.version }})
          
          ### Changes
          - Updated Service API documentation from OpenAPI spec
          - Regenerated Python SDK documentation using lazydocs (dynamically discovers all public modules)
          - Regenerated TypeScript SDK documentation using typedoc
          - Updated docs.json navigation with any new or removed modules
          - Fixed file casing for consistency
          - Fixed internal cross-reference links
        branch: update-reference-docs-${{ github.run_number }}
        delete-branch: true
        labels: |
          documentation
          automated
          weave
    
    - name: Display PR Link
      if: steps.create-pr.outputs.pull-request-number
      run: |
        PR_URL="https://github.com/${{ github.repository }}/pull/${{ steps.create-pr.outputs.pull-request-number }}"
        echo "📝 Draft PR created successfully!"
        echo "🔗 Review the changes at: $PR_URL"
        echo ""
        echo "::notice title=Pull Request Created::A draft PR has been created for review: $PR_URL"
