name: Mintlify Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Mintlify CLI
        run: npm install -g mintlify
        
      - name: Build documentation
        run: mintlify build
        
      - name: Deploy to Mintlify (main branch only)
        if: github.ref == 'refs/heads/main'
        run: mintlify deploy
        env:
          MINTLIFY_API_KEY: ${{ secrets.MINTLIFY_API_KEY }}
