name: Vale check
on:
  pull_request

jobs:
  vale:
    name: Vale check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            fail_on_error: false
            files: content
            reporter: github-pr-review
            filter_mode: added