name: Translate MD files

on: [workflow_dispatch]

defaults:
  run: { shell: bash }

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
        # save files to a file
        echo "${{ steps.changed-files.outputs.all_changed_files }}" > changed_files.txt
    - name: Run script
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pip install git+https://github.com/tcapelle/gpt_translate.git
        python3 scripts/translate.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Adding Translated docs!
      