name: Update Training API Documentation

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Mondays at 9:30 AM UTC (30 minutes after Service API)
    - cron: '30 9 * * 1'
  workflow_call:

jobs:
  update-training-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Generate timestamp
      id: timestamp
      run: |
        TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
        echo "Generated at: ${TIMESTAMP}"
        
    - name: Sync OpenAPI Specification
      id: sync-spec
      run: |
        echo "Syncing Training API specification from remote service..."
        OUTPUT=$(python scripts/reference-generation/training/sync_openapi_spec.py 2>&1)
        echo "$OUTPUT"
        
        # Check if spec changed
        if echo "$OUTPUT" | grep -q "Training API spec has changed"; then
          echo "spec_changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected in Training API spec"
        else
          echo "spec_changed=false" >> $GITHUB_OUTPUT
          echo "No changes in Training API spec"
        fi
        
    - name: Update Training API Landing Page
      if: steps.sync-spec.outputs.spec_changed == 'true'
      run: |
        echo "Updating Training API landing page with current endpoints..."
        python scripts/reference-generation/training/update_training_api_landing.py
        
    - name: Check for changes
      id: check-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected in repository"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
        
    - name: Create Pull Request
      if: steps.check-changes.outputs.has_changes == 'true'
      id: create-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: Update Training API documentation"
        title: "Update Training API documentation"
        draft: false
        body: |
          This PR updates the Training API documentation based on the latest OpenAPI specification.
          
          **Generated on**: ${{ steps.timestamp.outputs.timestamp }}
          **OpenAPI spec source**: https://api.training.wandb.ai/openapi.json
          
          ### Changes
          - Synced latest OpenAPI specification from the Training API service
          - Updated Training API landing page with current endpoints
          
          ### Review Checklist
          - [ ] Verify new endpoints are correctly listed
          - [ ] Check that removed endpoints (if any) are intentional
          - [ ] Confirm all Training API links work correctly
          
          ---
          *This PR was automatically generated by the Training API update workflow.*
        branch: update-training-api-${{ github.run_number }}
        delete-branch: true
        labels: |
          documentation
          automated
          training-api
    
    - name: Display Result
      run: |
        if [ "${{ steps.check-changes.outputs.has_changes }}" == "true" ]; then
          if [ -n "${{ steps.create-pr.outputs.pull-request-number }}" ]; then
            PR_URL="https://github.com/${{ github.repository }}/pull/${{ steps.create-pr.outputs.pull-request-number }}"
            echo "📝 PR created successfully!"
            echo "🔗 Review the changes at: $PR_URL"
            echo "::notice title=Pull Request Created::A PR has been created for Training API updates: $PR_URL"
          fi
        else
          echo "✅ Training API documentation is up to date"
          echo "::notice title=No Updates Needed::Training API documentation is already up to date"
        fi
